# Generated by Django 5.2.4 on 2025-08-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_otp_alter_customer_phone_alter_hairdresser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hairdresser',
        ),
        migrations.AddField(
            model_name='customer',
            name='hairdressers',
            field=models.ManyToManyField(related_name='customers', to='main_app.hairdresser'),
        ),
    ]
