# Generated by Django 5.2.4 on 2025-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_customer_hairdresser_customer_hairdressers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdresser',
            name='is_public_search',
            field=models.BooleanField(default=True, verbose_name='نمایش در جستجو مشتری ناشناس'),
        ),
    ]
