# Generated by Django 5.2.4 on 2025-08-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_hairdresser_is_public_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdresser',
            name='owner',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='customer_name',
            new_name='booker_name',
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.CharField(choices=[('scheduler', 'Scheduler'), ('booker', 'Booker')], default='booker', max_length=20),
        ),
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('family', models.CharField(max_length=64, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booker_owner', to='main_app.roleuser')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='booker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main_app.booker'),
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('family', models.CharField(max_length=64, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('bio', models.TextField()),
                ('is_public_search', models.BooleanField(default=True, verbose_name='نمایش در جستجو مشتری ناشناس')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_owner', to='main_app.roleuser')),
            ],
        ),
        migrations.AddField(
            model_name='booker',
            name='schedulers',
            field=models.ManyToManyField(related_name='bookers', to='main_app.scheduler'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduler',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main_app.scheduler'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('scheduler', 'date', 'time')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hairdresser',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Hairdresser',
        ),
    ]
